apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
        - name: test-api
          image: 816069129828.dkr.ecr.us-east-2.amazonaws.com/test-api-repo:latest
          ports:
            - containerPort: 80

