apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-server
    spec:
      containers:
      - name: test-api
        image: 816069129828.dkr.ecr.us-east-2.amazonaws.com/test-api-repo:latest
        ports:
        - containerPort: 80

